version: "3.9"

services:
  wui:
    build:
      context: ./src/Bootler.WUI
      dockerfile: Dockerfile 
    container_name: todo_wui
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      # Monta la configuraci√≥n personalizada de Nginx
      - ./src/Bootler.WUI/nginx/default.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:15-alpine
    container_name: todo_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pwd
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
